feat: upgraded circleci pipeline structure and parameters

diff --git a/sample-pipeline-circleci.yml b/sample-pipeline-circleci.yml
--- a/sample-pipeline-circleci.yml
+++ b/sample-pipeline-circleci.yml
@@ -2,11 +2,25 @@ version: 2.1
 workflows:
   semgrep:
     jobs:
-      - semgrep-full-scan
+      - semgrep-full-scan:
+          fail-blocking: false
+          report-filename: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-$(date +'%Y-%m-%d-%H-%M-%S')"
+
 jobs:
   semgrep-full-scan:
     docker:
       - image: cimg/python:3.13.2
+
+    parameters:
+      fail-blocking:
+        type: boolean
+        description: "Fail the pipeline if blocking issues are found. Values : true, false"
+        default: true
+      report-filename:
+        type: string
+        description: "Name of the exported report. Should not contain spaces and special characters except - and _"
+        default: '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-${CIRCLE_SHA1}-${CIRCLE_WORKFLOW_ID}'
+        # option with timestamp : '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-$(date +'%Y-%m-%d-%H-%M-%S')'
     steps:
       - checkout
 
@@ -17,27 +31,35 @@ jobs:
             git clone https://github.com/lux10n/semgrep2html.git
             pip install -r semgrep2html/requirements.txt
             mkdir /tmp/reports
-            echo "SCAN_TAGNAME=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH-$(date +'%Y-%m-%d-%H-%M-%S')" >> $BASH_ENV
+            echo <<parameters.report-filename>>
+            echo 'export SEMGREP_REPORT_FILENAME=<<parameters.report-filename>>' >> "$BASH_ENV"
 
       - run:
           name: Run scan
-          command: semgrep scan --config auto --json-output $SCAN_TAGNAME.json
+          command: |
+            semgrep scan --config auto --json-output _semgrep-findings.json
 
       - run:
           name : Generate report
-          command: python semgrep2html/parse-semgrep.py --input $SCAN_TAGNAME.json --output /tmp/reports/$SCAN_TAGNAME.html --project-name $CIRCLE_PROJECT_REPONAME --branch $CIRCLE_BRANCH
+          command: python semgrep2html/parse-semgrep.py --input _semgrep-findings.json --output /tmp/reports/$SEMGREP_REPORT_FILENAME.html --project-name $CIRCLE_PROJECT_REPONAME --branch $CIRCLE_BRANCH
 
       - store_artifacts:
           path: /tmp/reports
           destination: reports
 
-      - run : 
+      - run: 
           name: Fail if blocking issues exist
+          environment:
+            FAIL_BLOCKING: <<parameters.fail-blocking>>
           command: |
-            BLOCKING_ISSUES=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' $SCAN_TAGNAME.json)
+            BLOCKING_ISSUES=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' _semgrep-findings.json)
             if [ "$BLOCKING_ISSUES" -gt 0 ]; then
-              echo "[FAIL] Blocking issues detected! Please check the scanning steps for more details."
-              exit 1
+              if [ "$FAIL_BLOCKING" -eq 1 ]; then
+                echo "[FAIL] $BLOCKING_ISSUES blocking issues detected! Please check the scanning steps for more details."
+                exit 1
+              else
+                echo "[WARNING] $BLOCKING_ISSUES blocking issues detected, but pipeline will not fail due to configuration."
+              fi
             else
               echo "[SUCCESS] No blocking issues found. Closing..."
             fi
